# Homtask 1

In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)
a

tensor([[[ 0.6438, -0.4044, -1.1353, -0.0344,  0.7094],
         [ 0.1199,  0.1478, -2.1886,  0.4963,  1.4575],
         [ 1.7417,  2.2704,  0.0502,  0.0717,  1.1102],
         [ 1.3333, -0.5331, -2.0405,  0.4356, -0.5942]],

        [[-0.9678,  0.2846, -1.7106, -0.0943, -0.7252],
         [ 0.3364, -1.8796,  0.0110,  1.2617, -1.0446],
         [-1.0571, -1.3342,  0.8713, -0.1107,  1.3191],
         [-0.5701,  0.9426, -0.0308, -0.8096, -0.6101]],

        [[-1.0052,  2.1515,  0.6131, -0.6270,  1.0544],
         [ 0.1015, -0.8191,  1.8180,  0.5605,  0.5937],
         [ 0.8655,  0.1122,  0.3517, -0.1296, -0.1176],
         [ 0.6057,  0.0189,  1.3945,  1.0099,  0.3676]]])

In [3]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
b = a.reshape((6, 10))
b.shape

torch.Size([6, 10])

In [5]:
b

tensor([[ 0.6438, -0.4044, -1.1353, -0.0344,  0.7094,  0.1199,  0.1478, -2.1886,
          0.4963,  1.4575],
        [ 1.7417,  2.2704,  0.0502,  0.0717,  1.1102,  1.3333, -0.5331, -2.0405,
          0.4356, -0.5942],
        [-0.9678,  0.2846, -1.7106, -0.0943, -0.7252,  0.3364, -1.8796,  0.0110,
          1.2617, -1.0446],
        [-1.0571, -1.3342,  0.8713, -0.1107,  1.3191, -0.5701,  0.9426, -0.0308,
         -0.8096, -0.6101],
        [-1.0052,  2.1515,  0.6131, -0.6270,  1.0544,  0.1015, -0.8191,  1.8180,
          0.5605,  0.5937],
        [ 0.8655,  0.1122,  0.3517, -0.1296, -0.1176,  0.6057,  0.0189,  1.3945,
          1.0099,  0.3676]])

In [14]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b.reshape((-1, 5)).mul(torch.tensor([1, 4, 2, 2, 1])).reshape((6, 10))

tensor([[ 0.6438, -1.6176, -2.2707, -0.0688,  0.7094,  0.1199,  0.5913, -4.3772,
          0.9925,  1.4575],
        [ 1.7417,  9.0818,  0.1005,  0.1434,  1.1102,  1.3333, -2.1323, -4.0810,
          0.8713, -0.5942],
        [-0.9678,  1.1386, -3.4211, -0.1887, -0.7252,  0.3364, -7.5184,  0.0220,
          2.5235, -1.0446],
        [-1.0571, -5.3369,  1.7427, -0.2214,  1.3191, -0.5701,  3.7703, -0.0616,
         -1.6192, -0.6101],
        [-1.0052,  8.6059,  1.2262, -1.2541,  1.0544,  0.1015, -3.2766,  3.6360,
          1.1210,  0.5937],
        [ 0.8655,  0.4489,  0.7034, -0.2592, -0.1176,  0.6057,  0.0756,  2.7890,
          2.0197,  0.3676]])

In [16]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
b.mm(b.T)

tensor([[ 9.5683,  4.8283, -0.4652, -1.3432, -4.3878, -1.9061],
        [ 4.8283, 16.1970,  0.6615, -4.5598,  1.0444, -0.1864],
        [-0.4652,  0.6615, 10.8077, -4.1414,  1.5117, -0.2359],
        [-1.3432, -4.5598, -4.1414,  7.6512, -1.5154, -2.3113],
        [-4.3878,  1.0444,  1.5117, -1.5154, 12.1731,  2.9098],
        [-1.9061, -0.1864, -0.2359, -2.3113,  2.9098,  4.3829]])

In [22]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True) 
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)
y = x**3 + z - 75 * t

y.backward()
x.grad, z.grad, t.grad, y

(tensor(3.),
 tensor(1.),
 tensor(-75.),
 tensor(-148.5000, grad_fn=<SubBackward0>))

In [23]:
# Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [25]:
# Переведите его в формат numpy
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [67]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

import torch
from torch import nn
from torch import optim

linear = nn.Linear(2, 2)

criterion = nn.MSELoss()

optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

x = torch.randn(1, requires_grad=True)
w1 = torch.randn(1, requires_grad=True)
y = torch.tensor(x**w1 - 2 * x**2 + 5, requires_grad=False)

print(x, w1, y)

optimizer.zero_grad()

pred = linear(torch.cat((x, w1)))

loss = criterion(y, pred)
print('loss: ', loss, ' \nloss_item :', loss.item())

loss.backward()

# Веса до
print('BEFORE:\n','w: ', linear.weight)
print('b: ', linear.bias, '\n')

# Делаем шаг оптимизатора
optimizer.step()

# Веса после
print('AFTER:\n''w: ', linear.weight)
print('b: ', linear.bias)

tensor([0.3776], requires_grad=True) tensor([1.0164], requires_grad=True) tensor([5.0865])
loss:  tensor(35.5675, grad_fn=<MseLossBackward0>)  
loss_item : 35.56748580932617
BEFORE:
 w:  Parameter containing:
tensor([[-0.5022, -0.2458],
        [ 0.0193, -0.6786]], requires_grad=True)
b:  Parameter containing:
tensor([-0.0736, -0.5381], requires_grad=True) 

AFTER:
w:  Parameter containing:
tensor([[-0.4811, -0.1889],
        [ 0.0431, -0.6145]], requires_grad=True)
b:  Parameter containing:
tensor([-0.0176, -0.4751], requires_grad=True)


/tmp/ipykernel_278993/253412421.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x**w1 - 2 * x**2 + 5, requires_grad=False)


Из-за степени w1 не всегда может считаться, т.к. случайная величина. Можно заменить другим рандомом или просто проверять на значение.